{% set name = "suitcase-json-metadata" %}
{% set version = "0.2.0" %}
{% set sha256 = "e87b7ac608199ae70e9365b90fd772343ec7240244add925e5d3e91a085c99d4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python
    - event-model >=1.8.0
    - suitcase-utils

test:
  imports:
    - suitcase.json_metadata
    - suitcase.json_metadata.tests

about:
  home: https://blueskyproject.io/suitcase
  license: BSD (3-clause)
  license_family: BSD
  license_file: LICENSE
  summary: Export bluesky documents' metadata to JSON
  doc_url: https://blueskyproject.io/suitcase
  dev_url: https://github.com/bluesky/suitcase-json-metadata
